//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.22 at 08:28:14 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springsource.com/reward-network")
package rewards.ws.marshalling;
